-- Ejecutar como SYS o SYSTEM conectado al PDB XEPDB1.
-- Cambie la contraseña antes de ejecutar.

CREATE USER MONITOR_USER IDENTIFIED BY "12345";
GRANT CREATE SESSION TO MONITOR_USER;

GRANT SELECT ON V_$PROCESS TO MONITOR_USER;
GRANT SELECT ON V_$SESSION TO MONITOR_USER;
GRANT SELECT ON V_$RESOURCE_LIMIT TO MONITOR_USER;
GRANT SELECT ON V_$SESSION_LONGOPS TO MONITOR_USER;
GRANT SELECT ON V_$WAIT_CHAINS TO MONITOR_USER;
GRANT SELECT ON V_$VERSION TO MONITOR_USER;

-- Verificación
SELECT USER FROM DUAL;
